# Generated by Django 4.1.13 on 2024-04-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, upload_to='images/')),
            ],
        ),
    ]
